### ISSUE TITLE
falta bower al hace make iniciar (para el template de ember)

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-mu#2]
<pre>
ragnarok@ragnarok:/tmp$ mu

       /)   (\       
  .-._((,~"~.))_.-,    
   `-.   e e   ,-'    ¡Hola!, estás usando mu, un
     / ,o---o. \      asistente para crear y distribuir 
    ( ( .___. ) )     proyectos usando las mejores 
     ) `-----' (      tecnologías.
    /`-.__ __.-'\     
         ,8.          ¡muuuu! 
        /___\          
        `-&-'         versión: 0.0.14

 (consejo: pulsá las teclas 'CTRL C' si las cosas se ponen feas...)

? ¿Como se llamará tu aplicación? eee
? ¿Que tecnología te gustaría usar aquí? ember

Se ha creado el directorio eee

Te recomiendo ejecutar estos comandos para continuar: 

   cd eee
   make iniciar

y por último, para ver el resto de los comandos disponibles:

   make

Creando el directorio: eee
ragnarok@ragnarok:/tmp$ cd eee/
ragnarok@ragnarok:/tmp/eee$ make iniciar
npm install
npm WARN excluding symbolic link example/addons.css -> ../wrapped/addons.css
npm WARN excluding symbolic link example/addons.js -> ../wrapped/addons.js
npm WARN excluding symbolic link example/addons.map -> ../wrapped/addons.map
npm WARN excluding symbolic link example/ember-template-compiler.js -> ../bower_components/ember/ember-template-compiler.js
npm WARN excluding symbolic link example/ember-template-compiler.map -> ../bower_components/ember/ember-template-compiler.map
npm WARN excluding symbolic link example/ember.debug.js -> ../bower_components/ember/ember.debug.js
npm WARN excluding symbolic link example/addons.css -> ../wrapped/addons.css
npm WARN excluding symbolic link example/addons.js -> ../wrapped/addons.js
npm WARN excluding symbolic link example/addons.map -> ../wrapped/addons.map
npm WARN excluding symbolic link example/ember-template-compiler.js -> ../bower_components/ember/ember-template-compiler.js
npm WARN excluding symbolic link example/ember-template-compiler.map -> ../bower_components/ember/ember-template-compiler.map
npm WARN excluding symbolic link example/ember.debug.js -> ../bower_components/ember/ember.debug.js
ember-cli-inject-live-reload@1.3.1 node_modules/ember-cli-inject-live-reload

ember-export-application-global@1.0.2 node_modules/ember-export-application-global

ember-data@1.0.0-beta.16.1 node_modules/ember-data

ember-localstorage-adapter@0.5.2 node_modules/ember-localstorage-adapter

ember-cli-ic-ajax@0.1.1 node_modules/ember-cli-ic-ajax
└── ic-ajax@2.0.2

ember-cli-app-version@0.3.3 node_modules/ember-cli-app-version
└── git-repo-version@0.2.0 (git-repo-info@1.0.4)

ember-cli-dependency-checker@0.0.8 node_modules/ember-cli-dependency-checker
├── semver@4.3.3
└── chalk@0.5.1 (ansi-styles@1.1.0, supports-color@0.2.0, escape-string-regexp@1.0.3, has-ansi@0.1.0, strip-ansi@0.3.0)

broccoli-asset-rev@2.0.3 node_modules/broccoli-asset-rev
├── broccoli-asset-rewrite@1.0.5
├── rsvp@3.0.18
└── broccoli-filter@0.1.12 (broccoli-writer@0.1.1, promise-map-series@0.2.1, mkdirp@0.3.5, walk-sync@0.1.3, quick-temp@0.1.2, broccoli-kitchen-sink-helpers@0.2.6)

ember-cli-content-security-policy@0.4.0 node_modules/ember-cli-content-security-policy
└── body-parser@1.12.2 (content-type@1.0.1, raw-body@1.3.3, bytes@1.0.0, depd@1.0.1, qs@2.4.1, iconv-lite@0.4.7, debug@2.1.3, on-finished@2.2.0, type-is@1.6.1)

ember-cli-htmlbars@0.7.4 node_modules/ember-cli-htmlbars
├── ember-cli-version-checker@1.0.2 (semver@4.3.3)
└── broccoli-filter@0.1.12 (broccoli-writer@0.1.1, promise-map-series@0.2.1, walk-sync@0.1.3, mkdirp@0.3.5, quick-temp@0.1.2, broccoli-kitchen-sink-helpers@0.2.6, rsvp@3.0.18)

ember-cli-uglify@1.0.1 node_modules/ember-cli-uglify
└── broccoli-uglify-sourcemap@0.2.1 (source-map-url@0.3.0, walk-sync@0.1.3, symlink-or-copy@1.0.1, mkdirp@0.5.0, lodash-node@2.4.1, uglify-js@2.4.19, broccoli-writer@0.1.1)

ember-cli-qunit@0.3.9 node_modules/ember-cli-qunit
└── broccoli-jshint@0.5.5 (mkdirp@0.4.2, chalk@0.4.0, findup-sync@0.1.3, broccoli-filter@0.1.12, jshint@2.6.3)

ember-cli-babel@4.3.3 node_modules/ember-cli-babel
├── ember-cli-version-checker@1.0.2 (semver@4.3.3)
├── broccoli-filter@0.1.12 (broccoli-writer@0.1.1, promise-map-series@0.2.1, walk-sync@0.1.3, mkdirp@0.3.5, quick-temp@0.1.2, broccoli-kitchen-sink-helpers@0.2.6, rsvp@3.0.18)
└── broccoli-babel-transpiler@4.1.0 (clone@0.2.0, babel-core@4.7.16)

liquid-fire@0.19.2 node_modules/liquid-fire
├── ember-cli-version-checker@1.0.2 (semver@4.3.3)
├── broccoli-static-compiler@0.2.1 (symlink-or-copy@1.0.1, mkdirp@0.5.0, broccoli-kitchen-sink-helpers@0.2.6, broccoli-writer@0.1.1)
├── velocity-animate@1.2.2 (jquery@2.1.3)
├── broccoli-merge-trees@0.2.1 (symlink-or-copy@1.0.1, broccoli-writer@0.1.1, promise-map-series@0.2.1)
└── ember-cli-babel@4.1.0 (broccoli-filter@0.1.12, broccoli-babel-transpiler@4.1.0)

ember-cli@0.2.2 node_modules/ember-cli
├── ember-cli-copy-dereference@1.0.0
├── abbrev@1.0.5
├── js-string-escape@1.0.0
├── exit@0.1.2
├── strip-ansi@2.0.1 (ansi-regex@1.1.1)
├── debug@2.1.3 (ms@0.7.0)
├── symlink-or-copy@1.0.1 (copy-dereference@1.0.0)
├── promise-map-series@0.2.1 (rsvp@3.0.18)
├── temp@0.8.1 (rimraf@2.2.8)
├── http-proxy@1.10.1 (requires-port@0.0.0, eventemitter3@0.1.6)
├── broccoli-writer@0.1.1 (rsvp@3.0.18, quick-temp@0.1.2)
├── broccoli-caching-writer@0.5.5 (core-object@0.0.3, rsvp@3.0.18, lodash-node@2.4.1, quick-temp@0.1.2, broccoli-kitchen-sink-helpers@0.2.6)
├── broccoli-es3-safe-recast@2.0.0 (broccoli-filter@0.1.12, es3-safe-recast@2.0.1)
├── yam@0.0.18 (fs-extra@0.16.5, findup@0.1.5, lodash.merge@3.1.0)
├── rimraf@2.3.2 (glob@4.5.3)
├── markdown-it@4.0.3 (linkify-it@1.0.0, mdurl@1.0.0, uc.micro@1.0.0, entities@1.1.1, argparse@1.0.2)
├── broccoli-sourcemap-concat@0.4.3 (broccoli-caching-writer@0.5.3, combined-stream@0.0.7, mkdirp@0.5.0, rsvp@3.0.18, broccoli-kitchen-sink-helpers@0.2.6, lodash-node@2.4.1, fast-sourcemap-concat@0.2.4)
├── broccoli-sane-watcher@1.0.2 (broccoli-slow-trees@1.1.0, rsvp@3.0.18, sane@1.0.2)
├── markdown-it-terminal@0.0.2 (ansi-styles@2.0.1, lodash-node@3.6.0, cli-table@0.3.1, cardinal@0.5.0)
└── broccoli-es6modules@0.5.1 (walk-sync@0.1.3, rsvp@3.0.18, mkdirp@0.5.0, broccoli-kitchen-sink-helpers@0.2.6, broccoli-caching-writer@0.5.3, esperanto@0.6.27)
bower install
make: bower: No se encontró el programa
Makefile:32: recipe for target 'iniciar' failed
make: *** [iniciar] Error 127

</pre>

**Comment by hugoruscitti** [comment]
m... sip, ahora lo veo, lo mejor es incluir "bower" a package.json (para que lo instale npm) y luego usarlo de forma local... me lo asigno y aplico el arreglo mañana.
